Mon, 29 Nov 2021 15:19:32-run_all_case.py-run_all_case.py-[line:19]-INFO-[日志信息]: ==================================2021-11-29 15:19:32===================================
Mon, 29 Nov 2021 15:20:57-run_all_case.py-run_all_case.py-[line:19]-INFO-[日志信息]: ==================================2021-11-29 15:20:57===================================
Mon, 29 Nov 2021 15:24:51-pytest-Register_case.py-[line:30]-INFO-[日志信息]: 开始执行脚本test_Register：

Mon, 29 Nov 2021 15:24:51-test_Register-Assert.py-[line:30]-INFO-[日志信息]: statusCode true, expected_code is 200, statusCode is 200 
Mon, 29 Nov 2021 15:24:51-test_Register-Assert.py-[line:47]-INFO-[日志信息]: Response body msg == expected_msg, expected_msg is ,body_msg is  
Mon, 29 Nov 2021 15:24:51-pytest-Register_case.py-[line:60]-INFO-[日志信息]: 开始执行脚本test_No_Num：

Mon, 29 Nov 2021 15:24:52-test_No_Num-Assert.py-[line:30]-INFO-[日志信息]: statusCode true, expected_code is 200, statusCode is 200 
Mon, 29 Nov 2021 15:24:52-test_No_Num-Assert.py-[line:47]-INFO-[日志信息]: Response body msg == expected_msg, expected_msg is 请求参数错误,body_msg is 请求参数错误 
Mon, 29 Nov 2021 15:24:52-pytest-Register_case.py-[line:85]-INFO-[日志信息]: 开始执行脚本test_Wrong_Num：

Mon, 29 Nov 2021 15:24:52-test_Wrong_Num-Assert.py-[line:30]-INFO-[日志信息]: statusCode true, expected_code is 200, statusCode is 200 
Mon, 29 Nov 2021 15:24:52-test_Wrong_Num-Assert.py-[line:47]-INFO-[日志信息]: Response body msg == expected_msg, expected_msg is 手机号格式错误,body_msg is 手机号格式错误 
Mon, 29 Nov 2021 15:24:52-pytest-Register_case.py-[line:110]-INFO-[日志信息]: 开始执行脚本test_Illegal_Character：

Mon, 29 Nov 2021 15:24:52-test_Illegal_Character-Assert.py-[line:30]-INFO-[日志信息]: statusCode true, expected_code is 200, statusCode is 200 
Mon, 29 Nov 2021 15:24:52-test_Illegal_Character-Assert.py-[line:47]-INFO-[日志信息]: Response body msg == expected_msg, expected_msg is 手机号格式错误,body_msg is 手机号格式错误 
Mon, 29 Nov 2021 15:24:52-pytest-Register_case.py-[line:135]-INFO-[日志信息]: 开始执行脚本test_Registered_Num：

Mon, 29 Nov 2021 15:24:52-test_Registered_Num-Assert.py-[line:30]-INFO-[日志信息]: statusCode true, expected_code is 200, statusCode is 200 
Mon, 29 Nov 2021 15:24:52-test_Registered_Num-Assert.py-[line:50]-ERROR-[日志信息]: Response body msg != expected_msg, expected_msg is 手机号已注册，请登录,body_msg is 手机号已注册 
Mon, 29 Nov 2021 15:24:53-pytest-Register_case.py-[line:160]-INFO-[日志信息]: 开始执行脚本test_Pwd_Error：

Mon, 29 Nov 2021 15:24:53-test_Pwd_Error-Assert.py-[line:30]-INFO-[日志信息]: statusCode true, expected_code is 200, statusCode is 200 
Mon, 29 Nov 2021 15:24:53-test_Pwd_Error-Assert.py-[line:47]-INFO-[日志信息]: Response body msg == expected_msg, expected_msg is ,body_msg is  
Mon, 29 Nov 2021 15:24:53-pytest-Register_case.py-[line:186]-INFO-[日志信息]: 开始执行脚本test_Pwd_No_Capitalization：

Mon, 29 Nov 2021 15:24:53-test_Pwd_No_Capitalization-Assert.py-[line:30]-INFO-[日志信息]: statusCode true, expected_code is 200, statusCode is 200 
Mon, 29 Nov 2021 15:24:53-test_Pwd_No_Capitalization-Assert.py-[line:47]-INFO-[日志信息]: Response body msg == expected_msg, expected_msg is ,body_msg is  
Mon, 29 Nov 2021 15:24:53-pytest-Register_case.py-[line:212]-INFO-[日志信息]: 开始执行脚本test_No_Pwd：

Mon, 29 Nov 2021 15:24:54-test_No_Pwd-Assert.py-[line:30]-INFO-[日志信息]: statusCode true, expected_code is 200, statusCode is 200 
Mon, 29 Nov 2021 15:24:54-test_No_Pwd-Assert.py-[line:47]-INFO-[日志信息]: Response body msg == expected_msg, expected_msg is 请求参数错误,body_msg is 请求参数错误 
Mon, 29 Nov 2021 15:24:54-pytest-Register_case.py-[line:237]-INFO-[日志信息]: 开始执行脚本test_CodeError：

Mon, 29 Nov 2021 15:24:54-test_CodeError-Assert.py-[line:30]-INFO-[日志信息]: statusCode true, expected_code is 200, statusCode is 200 
Mon, 29 Nov 2021 15:24:54-test_CodeError-Assert.py-[line:47]-INFO-[日志信息]: Response body msg == expected_msg, expected_msg is 验证码无效，请重新获取,body_msg is 验证码无效，请重新获取 
Mon, 29 Nov 2021 15:24:54-pytest-Register_case.py-[line:265]-INFO-[日志信息]: 开始执行脚本test_No_Code：

Mon, 29 Nov 2021 15:24:54-test_No_Code-Assert.py-[line:30]-INFO-[日志信息]: statusCode true, expected_code is 200, statusCode is 200 
Mon, 29 Nov 2021 15:24:54-test_No_Code-Assert.py-[line:47]-INFO-[日志信息]: Response body msg == expected_msg, expected_msg is 请求参数错误,body_msg is 请求参数错误 
Mon, 29 Nov 2021 15:47:47-run_all_case.py-run_all_case.py-[line:19]-INFO-[日志信息]: ==================================2021-11-29 15:47:47===================================
Mon, 29 Nov 2021 17:39:30-__main__-Logs.py-[line:65]-DEBUG-[日志信息]: I am a debug message
Mon, 29 Nov 2021 17:39:30-__main__-Logs.py-[line:66]-INFO-[日志信息]: I am a info message
Mon, 29 Nov 2021 17:39:30-__main__-Logs.py-[line:67]-WARNING-[日志信息]: I am a warning message
Mon, 29 Nov 2021 17:39:30-__main__-Logs.py-[line:68]-ERROR-[日志信息]: I am a error message
Mon, 29 Nov 2021 17:39:30-__main__-Logs.py-[line:69]-CRITICAL-[日志信息]: I am a critical message
Mon, 29 Nov 2021 17:41:12-_jb_pytest_runner.py-Login_case.py-[line:68]-INFO-[日志信息]: 开始执行脚本test_login：

Mon, 29 Nov 2021 17:41:12-test_login-Assert.py-[line:30]-INFO-[日志信息]: statusCode true, expected_code is 200, statusCode is 200 
Mon, 29 Nov 2021 17:41:12-test_login-Assert.py-[line:47]-INFO-[日志信息]: Response body msg == expected_msg, expected_msg is ,body_msg is  
Mon, 29 Nov 2021 17:41:38-_jb_pytest_runner.py-Login_case.py-[line:68]-INFO-[日志信息]: 开始执行脚本test_login：

Mon, 29 Nov 2021 17:41:39-test_login-Assert.py-[line:30]-INFO-[日志信息]: statusCode true, expected_code is 200, statusCode is 200 
Mon, 29 Nov 2021 17:41:39-test_login-Assert.py-[line:47]-INFO-[日志信息]: Response body msg == expected_msg, expected_msg is ,body_msg is  
Mon, 29 Nov 2021 17:41:39-_jb_pytest_runner.py-Login_case.py-[line:94]-INFO-[日志信息]: 开始执行脚本test_no_num：

Mon, 29 Nov 2021 17:41:39-test_no_num-Assert.py-[line:30]-INFO-[日志信息]: statusCode true, expected_code is 200, statusCode is 200 
Mon, 29 Nov 2021 17:41:39-test_no_num-Assert.py-[line:47]-INFO-[日志信息]: Response body msg == expected_msg, expected_msg is 请求参数错误,body_msg is 请求参数错误 
Mon, 29 Nov 2021 17:41:39-_jb_pytest_runner.py-Login_case.py-[line:120]-INFO-[日志信息]: 开始执行脚本test_nonexistent_num：

Mon, 29 Nov 2021 17:41:39-test_nonexistent_num-Assert.py-[line:30]-INFO-[日志信息]: statusCode true, expected_code is 200, statusCode is 200 
Mon, 29 Nov 2021 17:41:39-test_nonexistent_num-Assert.py-[line:47]-INFO-[日志信息]: Response body msg == expected_msg, expected_msg is 请求参数错误,body_msg is 请求参数错误 
Mon, 29 Nov 2021 17:41:39-_jb_pytest_runner.py-Login_case.py-[line:147]-INFO-[日志信息]: 开始执行脚本test_Num_Illegal_Character：

Mon, 29 Nov 2021 17:41:39-test_Num_Illegal_Character-Assert.py-[line:30]-INFO-[日志信息]: statusCode true, expected_code is 200, statusCode is 200 
Mon, 29 Nov 2021 17:41:39-test_Num_Illegal_Character-Assert.py-[line:50]-ERROR-[日志信息]: Response body msg != expected_msg, expected_msg is 手机号或密码错误，请重试,body_msg is 帐号未注册 
Mon, 29 Nov 2021 17:41:39-_jb_pytest_runner.py-Login_case.py-[line:201]-INFO-[日志信息]: 开始执行脚本test_wrong_num：

Mon, 29 Nov 2021 17:41:40-test_wrong_num-Assert.py-[line:30]-INFO-[日志信息]: statusCode true, expected_code is 200, statusCode is 200 
Mon, 29 Nov 2021 17:41:40-test_wrong_num-Assert.py-[line:50]-ERROR-[日志信息]: Response body msg != expected_msg, expected_msg is 手机号或密码错误，请重试,body_msg is 帐号未注册 
Mon, 29 Nov 2021 17:41:40-_jb_pytest_runner.py-Login_case.py-[line:228]-INFO-[日志信息]: 开始执行脚本test_no_pwd：

Mon, 29 Nov 2021 17:41:40-test_no_pwd-Assert.py-[line:30]-INFO-[日志信息]: statusCode true, expected_code is 200, statusCode is 200 
Mon, 29 Nov 2021 17:41:40-test_no_pwd-Assert.py-[line:47]-INFO-[日志信息]: Response body msg == expected_msg, expected_msg is 请求参数错误,body_msg is 请求参数错误 
Mon, 29 Nov 2021 17:41:40-_jb_pytest_runner.py-Login_case.py-[line:282]-INFO-[日志信息]: 开始执行脚本test_no_num_pwd：

Mon, 29 Nov 2021 17:41:40-test_no_num_pwd-Assert.py-[line:30]-INFO-[日志信息]: statusCode true, expected_code is 200, statusCode is 200 
Mon, 29 Nov 2021 17:41:40-test_no_num_pwd-Assert.py-[line:47]-INFO-[日志信息]: Response body msg == expected_msg, expected_msg is 请求参数错误,body_msg is 请求参数错误 
Mon, 29 Nov 2021 17:41:40-_jb_pytest_runner.py-Login_case.py-[line:309]-INFO-[日志信息]: 开始执行脚本test_wrong_pwd：

Mon, 29 Nov 2021 17:41:40-_jb_pytest_runner.py-Login_case.py-[line:315]-INFO-[日志信息]: login result: times=0, msg=手机号或密码错误，请重试.

Mon, 29 Nov 2021 17:41:40-_jb_pytest_runner.py-Login_case.py-[line:315]-INFO-[日志信息]: login result: times=1, msg=手机号或密码错误，请重试.

Mon, 29 Nov 2021 17:41:40-_jb_pytest_runner.py-Login_case.py-[line:315]-INFO-[日志信息]: login result: times=2, msg=手机号或密码错误，请重试.

Mon, 29 Nov 2021 17:41:41-_jb_pytest_runner.py-Login_case.py-[line:315]-INFO-[日志信息]: login result: times=3, msg=手机号或密码错误，请重试.

Mon, 29 Nov 2021 17:41:41-_jb_pytest_runner.py-Login_case.py-[line:315]-INFO-[日志信息]: login result: times=4, msg=手机号或密码错误，请重试.

Mon, 29 Nov 2021 17:41:41-_jb_pytest_runner.py-Login_case.py-[line:315]-INFO-[日志信息]: login result: times=5, msg=连续超过 6 次错误，请于 5 分钟后重新登录.

Mon, 29 Nov 2021 17:41:41-_jb_pytest_runner.py-Login_case.py-[line:315]-INFO-[日志信息]: login result: times=6, msg=连续超过 6 次错误，请于 5 分钟后重新登录.

Mon, 29 Nov 2021 17:41:41-_jb_pytest_runner.py-Login_case.py-[line:315]-INFO-[日志信息]: login result: times=7, msg=连续超过 6 次错误，请于 5 分钟后重新登录.

Mon, 29 Nov 2021 17:41:41-_jb_pytest_runner.py-Login_case.py-[line:315]-INFO-[日志信息]: login result: times=8, msg=连续超过 6 次错误，请于 5 分钟后重新登录.

Mon, 29 Nov 2021 17:41:42-_jb_pytest_runner.py-Login_case.py-[line:315]-INFO-[日志信息]: login result: times=9, msg=连续超过 6 次错误，请于 5 分钟后重新登录.

Mon, 29 Nov 2021 17:41:42-_jb_pytest_runner.py-Login_case.py-[line:339]-INFO-[日志信息]: 开始执行脚本test_code_login：

Mon, 29 Nov 2021 17:41:42-test_code_login-Assert.py-[line:30]-INFO-[日志信息]: statusCode true, expected_code is 200, statusCode is 200 
Mon, 29 Nov 2021 17:41:42-test_code_login-Assert.py-[line:47]-INFO-[日志信息]: Response body msg == expected_msg, expected_msg is ,body_msg is  
Mon, 29 Nov 2021 17:42:47-run_all_case.py-run_all_case.py-[line:19]-INFO-[日志信息]: ==================================2021-11-29 17:42:47===================================
Mon, 29 Nov 2021 17:43:53-run_all_case.py-run_all_case.py-[line:19]-INFO-[日志信息]: ==================================2021-11-29 17:43:53===================================
Mon, 29 Nov 2021 17:44:39-run_all_case.py-run_all_case.py-[line:19]-INFO-[日志信息]: ==================================2021-11-29 17:44:39===================================
Mon, 29 Nov 2021 17:44:39-run_all_case.py-Login_case.py-[line:68]-INFO-[日志信息]: 开始执行脚本test_login：

Mon, 29 Nov 2021 17:44:39-test_login-Assert.py-[line:30]-INFO-[日志信息]: statusCode true, expected_code is 200, statusCode is 200 
Mon, 29 Nov 2021 17:44:39-test_login-Assert.py-[line:47]-INFO-[日志信息]: Response body msg == expected_msg, expected_msg is ,body_msg is  
Mon, 29 Nov 2021 17:44:39-run_all_case.py-Login_case.py-[line:94]-INFO-[日志信息]: 开始执行脚本test_no_num：

Mon, 29 Nov 2021 17:44:39-test_no_num-Assert.py-[line:30]-INFO-[日志信息]: statusCode true, expected_code is 200, statusCode is 200 
Mon, 29 Nov 2021 17:44:39-test_no_num-Assert.py-[line:47]-INFO-[日志信息]: Response body msg == expected_msg, expected_msg is 请求参数错误,body_msg is 请求参数错误 
Mon, 29 Nov 2021 17:44:39-run_all_case.py-Login_case.py-[line:120]-INFO-[日志信息]: 开始执行脚本test_nonexistent_num：

Mon, 29 Nov 2021 17:44:40-test_nonexistent_num-Assert.py-[line:30]-INFO-[日志信息]: statusCode true, expected_code is 200, statusCode is 200 
Mon, 29 Nov 2021 17:44:40-test_nonexistent_num-Assert.py-[line:47]-INFO-[日志信息]: Response body msg == expected_msg, expected_msg is 请求参数错误,body_msg is 请求参数错误 
Mon, 29 Nov 2021 17:44:40-run_all_case.py-Login_case.py-[line:147]-INFO-[日志信息]: 开始执行脚本test_Num_Illegal_Character：

Mon, 29 Nov 2021 17:44:40-test_Num_Illegal_Character-Assert.py-[line:30]-INFO-[日志信息]: statusCode true, expected_code is 200, statusCode is 200 
Mon, 29 Nov 2021 17:44:40-test_Num_Illegal_Character-Assert.py-[line:50]-ERROR-[日志信息]: Response body msg != expected_msg, expected_msg is 手机号或密码错误，请重试,body_msg is 帐号未注册 
Mon, 29 Nov 2021 17:44:40-run_all_case.py-Login_case.py-[line:201]-INFO-[日志信息]: 开始执行脚本test_wrong_num：

Mon, 29 Nov 2021 17:44:40-test_wrong_num-Assert.py-[line:30]-INFO-[日志信息]: statusCode true, expected_code is 200, statusCode is 200 
Mon, 29 Nov 2021 17:44:40-test_wrong_num-Assert.py-[line:50]-ERROR-[日志信息]: Response body msg != expected_msg, expected_msg is 手机号或密码错误，请重试,body_msg is 帐号未注册 
Mon, 29 Nov 2021 17:44:40-run_all_case.py-Login_case.py-[line:228]-INFO-[日志信息]: 开始执行脚本test_no_pwd：

Mon, 29 Nov 2021 17:44:40-test_no_pwd-Assert.py-[line:30]-INFO-[日志信息]: statusCode true, expected_code is 200, statusCode is 200 
Mon, 29 Nov 2021 17:44:40-test_no_pwd-Assert.py-[line:47]-INFO-[日志信息]: Response body msg == expected_msg, expected_msg is 请求参数错误,body_msg is 请求参数错误 
Mon, 29 Nov 2021 17:44:40-run_all_case.py-Login_case.py-[line:282]-INFO-[日志信息]: 开始执行脚本test_no_num_pwd：

Mon, 29 Nov 2021 17:44:41-test_no_num_pwd-Assert.py-[line:30]-INFO-[日志信息]: statusCode true, expected_code is 200, statusCode is 200 
Mon, 29 Nov 2021 17:44:41-test_no_num_pwd-Assert.py-[line:47]-INFO-[日志信息]: Response body msg == expected_msg, expected_msg is 请求参数错误,body_msg is 请求参数错误 
Mon, 29 Nov 2021 17:44:41-run_all_case.py-Login_case.py-[line:309]-INFO-[日志信息]: 开始执行脚本test_wrong_pwd：

Mon, 29 Nov 2021 17:44:41-run_all_case.py-Login_case.py-[line:315]-INFO-[日志信息]: login result: times=0, msg=连续超过 6 次错误，请于 5 分钟后重新登录.

Mon, 29 Nov 2021 17:44:41-run_all_case.py-Login_case.py-[line:315]-INFO-[日志信息]: login result: times=1, msg=连续超过 6 次错误，请于 5 分钟后重新登录.

Mon, 29 Nov 2021 17:44:41-run_all_case.py-Login_case.py-[line:315]-INFO-[日志信息]: login result: times=2, msg=连续超过 6 次错误，请于 5 分钟后重新登录.

Mon, 29 Nov 2021 17:44:41-run_all_case.py-Login_case.py-[line:315]-INFO-[日志信息]: login result: times=3, msg=连续超过 6 次错误，请于 5 分钟后重新登录.

Mon, 29 Nov 2021 17:44:41-run_all_case.py-Login_case.py-[line:315]-INFO-[日志信息]: login result: times=4, msg=连续超过 6 次错误，请于 5 分钟后重新登录.

Mon, 29 Nov 2021 17:44:42-run_all_case.py-Login_case.py-[line:315]-INFO-[日志信息]: login result: times=5, msg=连续超过 6 次错误，请于 5 分钟后重新登录.

Mon, 29 Nov 2021 17:44:42-run_all_case.py-Login_case.py-[line:315]-INFO-[日志信息]: login result: times=6, msg=连续超过 6 次错误，请于 5 分钟后重新登录.

Mon, 29 Nov 2021 17:44:42-run_all_case.py-Login_case.py-[line:315]-INFO-[日志信息]: login result: times=7, msg=连续超过 6 次错误，请于 5 分钟后重新登录.

Mon, 29 Nov 2021 17:44:42-run_all_case.py-Login_case.py-[line:315]-INFO-[日志信息]: login result: times=8, msg=连续超过 6 次错误，请于 5 分钟后重新登录.

Mon, 29 Nov 2021 17:44:42-run_all_case.py-Login_case.py-[line:315]-INFO-[日志信息]: login result: times=9, msg=连续超过 6 次错误，请于 5 分钟后重新登录.

Mon, 29 Nov 2021 17:44:43-run_all_case.py-Login_case.py-[line:339]-INFO-[日志信息]: 开始执行脚本test_code_login：

Mon, 29 Nov 2021 17:44:43-test_code_login-Assert.py-[line:30]-INFO-[日志信息]: statusCode true, expected_code is 200, statusCode is 200 
Mon, 29 Nov 2021 17:44:43-test_code_login-Assert.py-[line:47]-INFO-[日志信息]: Response body msg == expected_msg, expected_msg is ,body_msg is  
